spring:
  data:
    mongodb:
      username: adminUser
      password: securePassword123
      host: localhost
      port: 27017
      database: customers
      authentication-database: admin
server:
  port: 8090