spring:
  data:
    mongodb:
      username: adminUser
      password: securePassword123
      host: localhost
      port: 27017
      database: customers
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:demo.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:demo.ecommerce.kafka.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: bekzodnosirov02@gmail.com
    password: dbvrilpoezxlnyyn
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040

#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=bekzodnosirov02@gmail.com
#  spring.mail.password=dbvrilpoezxlnyyn
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.connectiontimeout=5000
#  spring.mail.properties.mail.smtp.timeout=5000
#  spring.mail.properties.mail.smtp.writetimeout=5000
#  spring.mail.properties.mail.smtp.starttls.enable=true
